---
title: 'Data Challenge #2'
authors: "Brandon Wolff, Zachary Heinemann, and Stephanie Langeland"
due date: "3/22/2017"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1.	Ask two (2) questions that might help you understand better the dynamics of violence contained on our datas et. Apply one algorithm per question and share your insights from each analysis. [50 pts] Remember: a non-finding is also a finding! It tells you whether a question is worth pursuing further or not.
  *
  
  * 

##1a	perform the necessary transformations in your data - if any are needed, and explain why you did that
  * 
  
##1b	show the output from your analysis in a consumable form
  * 
  
##1c	be explicit about the limitations of your anaylisis, due to estimation or to the data itself
  * 
  
##1d	did you find something interesting? what is that? does your finding suggest this question is worth
  * pursuing further? why or why not?
  
##1e	if you did not find something interesting, explain why, and whether there is some additional information
  * that would help in answering your question
  
##1f	provide your code, and a single visualization per question that summarizes your finding
  * 
  
##1g	phrase your finding for each question in two ways:

##1g-1	one sentence that summarizes your insight
  * 

##1g-2	one paragraph that reflects all nuance in your insight
  * 
        
##1h	make sure to also include your code
  * 
  
#2.	Formulate two (2) conditional hypotheses that you seek to investigate with the data. One of your hypotheses should condition on two variables (as the example on the slides), and the other should condition on three variables. [50 pts]
  * 
  
  * 
  
##2a	formulate each one of your hypotheses explicitly in substantive terms (as opposed to statistical terms) using 2-3 lines at most
  * 
  
##2b	show exactly how each one of your hypotheses translates into the marginal effect that you will seek to estimate from the data
  * 
  
##2c	show the output from your analysis in a consumable form
  * 
  
##2d	show all your computations to estimate the corresponding marginal effect and its standard error
  * 
  
##2e	be explicit in your assumptions
  * 
  
##2f	be explicit in the limitations of your inferences
  * 
  
##2g	phrase your finding for each question in two ways:
##2g-1	one sentence that summarizes your insight
  * 
  
##2g-2	one paragraph that reflects all nuance in your insight
  * 
  
##2h	make sure to also include your code

This is a team assignment. Please create a file on your team GitHub repo where you answer the challenge, including links to your code, and graphs.

